# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JBChart' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JBChart

  target 'JBChartTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'p1m3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for p1m3

pod 'Firebase/Database'
pod 'Firebase/Core’

  target 'p1m3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'p1m3UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
